"""Tests for the APIKeyMiddleware (auth on /api/* endpoints)."""


def test_no_key_set_passes_through(test_client, monkeypatch):
    monkeypatch.setenv("INSTRUMATE_API_KEY", "")
    assert test_client.get("/api/apps").status_code == 200


def test_health_is_exempt_even_when_key_set(test_client, monkeypatch):
    """/api/health must always be reachable for liveness checks."""
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    assert test_client.get("/api/health").status_code == 200


def test_protected_route_requires_key(test_client, monkeypatch):
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    resp = test_client.get("/api/apps")
    assert resp.status_code == 401
    assert "api key" in resp.json()["detail"].lower()


def test_protected_route_rejects_wrong_key(test_client, monkeypatch):
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    resp = test_client.get("/api/apps", headers={"X-API-Key": "wrong"})
    assert resp.status_code == 401


def test_protected_route_accepts_correct_key(test_client, monkeypatch):
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    resp = test_client.get("/api/apps", headers={"X-API-Key": "secret"})
    assert resp.status_code == 200


def test_non_api_path_passes_through(test_client, monkeypatch):
    """Routes outside /api/ (e.g. /docs, /openapi.json) must not be gated."""
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    # /openapi.json is auto-generated by FastAPI and lives outside /api/
    assert test_client.get("/openapi.json").status_code == 200


def test_post_endpoint_also_gated(test_client, monkeypatch):
    """POST endpoints must require the key, not just GETs."""
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    resp = test_client.post(
        "/api/analyze",
        files={"file": ("a.apk", b"PK\x03\x04", "application/octet-stream")},
    )
    assert resp.status_code == 401


def test_empty_header_is_rejected(test_client, monkeypatch):
    """An empty X-API-Key is treated the same as missing."""
    monkeypatch.setenv("INSTRUMATE_API_KEY", "secret")
    resp = test_client.get("/api/apps", headers={"X-API-Key": ""})
    assert resp.status_code == 401


def test_key_is_case_sensitive(test_client, monkeypatch):
    """Keys are compared byte-for-byte — case matters."""
    monkeypatch.setenv("INSTRUMATE_API_KEY", "AbCdEf")
    assert test_client.get("/api/apps", headers={"X-API-Key": "abcdef"}).status_code == 401
    assert test_client.get("/api/apps", headers={"X-API-Key": "AbCdEf"}).status_code == 200
